### ISSUE TITLE
Improve code quality

### ISSUE THREAD

**Issue by 12joan** [12joan/twitter-client#1]
The `twitter.ts` is a bit of a mess right now

**Comment by Elham-EN** [comment]
Hello @12joan ,

I'm interested in contributing to this project, and this seems like a good first issue for me.

I've noticed that you've mentioned the twitter.ts file needs some improvements in terms of code quality. Could you please provide some more specific details about what you believe needs improving? Is it related to readability, efficiency, adherence to certain coding practices, or something else?

Once I have a better understanding of the specific improvements you're looking for, I'd be happy to start working on it.

**Comment by Elham-EN** [comment]
Here is my recommendation how you can improve your codebase.
1) Securely store credentials, Instead of hard-coding credentials and store them in .env file
2) Improve error handling, add explicit error handling after each fetch call and provide meaningful error messages.
3) Split code into modules. This file seems to be doing a lot of things. Consider splitting it into separate modules based   on functionality. For example, you could have one module for interacting with the Twitter API, another for handling the Redis cache, and another for combining everything to fetch tweets.
4) Document Your Code: Add comments to your code to explain what each part is doing. This will make it easier for others (and you in the future) to understand the code.
5) The code uses a mix of async/await and .then syntax for promises. While this is not necessarily a problem, sticking to one style (preferably async/await as it's easier to read) could make the code cleaner.

I can help you with this if needed.

**Comment by 12joan** [comment]
Hi @Elham-EN,

Thanks for offering to help improve the code quality. What I mainly had in mind was your third point, splitting the code into modules, but your other suggestions would be worthwhile too.

I'm not sure there's any point in storing the credentials securely, though, since they're taken from decompiled Twitter clients. We're relying on Twitter not wanting to revoke these credentials since this would break their own apps.

**Comment by wangy556** [comment]
Hi @12joan and @Elham-EN 

I'd be happy to add documentation to the server.ts and twitter.ts file if you'd like.

**Comment by 12joan** [comment]
@wangy556 Sure! That would be a great help 🙂
